# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_desc', models.TextField()),
                ('vacancy_count', models.IntegerField(default=0)),
                ('job_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Open'), (3, 'Close')], null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
